local PlayerState = require("subread.player_state")

describe("PlayerState.parse", function()
    it("reads a playing report", function()
        local state, err = PlayerState.parse("playing=1;position=96153;speed=1.5;package=de.ph1b.audiobook")
        assert.is_nil(err)
        assert.is_true(state.playing)
        assert.near(96.153, state.position, 1e-9)
        assert.equals(1.5, state.speed)
        assert.equals("de.ph1b.audiobook", state.package)
    end)

    it("reads a paused report", function()
        local state = PlayerState.parse("playing=0;position=0;speed=1.0;package=p")
        assert.is_false(state.playing)
        assert.equals(0, state.position)
    end)

    it("gives no position for a player without one", function()
        local state = PlayerState.parse("playing=1;position=-1;speed=1.0;package=p")
        assert.is_true(state.playing)
        assert.is_nil(state.position)
    end)

    it("returns the error name of a problem line", function()
        local state, err = PlayerState.parse("error=no_player")
        assert.is_nil(state)
        assert.equals("no_player", err)
        state, err = PlayerState.parse("error=no_notification_access")
        assert.is_nil(state)
        assert.equals("no_notification_access", err)
    end)

    it("rejects an empty or broken line", function()
        local state, err = PlayerState.parse(nil)
        assert.is_nil(state)
        assert.equals("empty", err)
        state, err = PlayerState.parse("")
        assert.equals("empty", err)
        state, err = PlayerState.parse("hello")
        assert.equals("malformed", err)
        state, err = PlayerState.parse("playing=1;position=abc")
        assert.equals("malformed", err)
    end)

    it("falls back to speed 1 for a missing or zero speed", function()
        assert.equals(1.0, PlayerState.parse("playing=1;position=5").speed)
        assert.equals(1.0, PlayerState.parse("playing=1;position=5;speed=0").speed)
    end)

    it("round trips a position through the seek argument", function()
        for _, seconds in ipairs({ 0, 0.001, 1, 96.153, 3600.5, 12345.6789 }) do
            local argument = PlayerState.seekArgument(seconds)
            assert.is_not_nil(argument:match("^%d+$"))
            local back = PlayerState.parse("playing=0;position=" .. argument)
            assert.near(seconds, back.position, 0.0005)
        end
        assert.equals("0", PlayerState.seekArgument(-3))
    end)
end)
